apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: streamlit-app
  name: streamlit-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: streamlit-app
  template:
    metadata:
      labels:
        app: streamlit-app
    spec:
      containers:
      - image: lopesina/streamlit-apps-nfl:dev
        name: streamlit-app
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
      imagePullSecrets:
      - name: regcred
