apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: streamlit-app

spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: streamlit-app
 minReplicas: 1
 maxReplicas: 3
 targetCPUUtilizationPercentage: 80
